@startuml
top to bottom direction

skinparam backgroundColor white
skinparam shadowing false
skinparam ArrowThickness 1
skinparam activity {
  BackgroundColor white
  BorderColor black
  FontSize 12
}

title Visitor Screen Flow

start
:Temporary Access Request;
:Temporary Ticket Detail;
:Parking Availability Map;
:Parking Exit and Payment;
:Temporary Session Closed;
stop

@enduml